// <auto-generated />
namespace TussoTechWebsite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_customer_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_customer_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201510021054013_Update_customer_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
